import Link from 'next/link'
import Head from "next/head";
import { clsx } from "clsx";
import React from 'react';
import { useSession, signIn, signOut } from "next-auth/react"
import type { NextPage } from 'next'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Header: NextPage = () => {
  const { data: session } = useSession()

  console.log(session)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex items-center justify-between flex-wrap bg-[#eeedf0] p-6">
        <div className="flex items-center text-white mr-6">
          <svg className="fill-current  rounded-3xl h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
          <Link href="/" className="text-s">
          <h1
            className={clsx(
              "sm:text[2rem] text-xl font-extrabold text-white",
              "tracking-tight"
            )}
          >
            Studio<span className="text-[hsl(280,55%,74%)]">Hub</span>
          </h1>
          </Link>
          
        </div>
        <div>
          <div className={clsx(
                  "text-xs rounded-lg bg-[#C68EDA] px-3 py-2",
                  "w-full text-white hover:bg-[#B384C8]"
                )}>
            {session && session.user ? (
              <button onClick={() => {signOut()}}>Log Out of GitHub</button>
            ) : (
              <button onClick={() => signIn()}>Log In to GitHub</button>
            )}
          </div>
            {/* <div className={clsx(
                  "text-xs rounded-lg bg-[#C68EDA] px-3 py-2",
                  "w-full text-white hover:bg-[#B384C8]"
                )}>
              <Link href="/new-page" className="text-s">Log In to Github</Link>
            </div> */}
        </div>
      </nav>
    </div>
  )
}

export default Header